### ISSUE TITLE
Some missing things here...

### ISSUE THREAD

**Issue by TimNagle-McNaughton** [fairaque1999/mars_glacier_boulders#1]
Looks like you forgot to link to the publication.

Scripts/boulder_density_plots/ seems to be empty too?

Also all your readme's seem to be empty.

Cool paper though!

**Comment by fairaque1999** [comment]
Thank you fo noticing! Seems like my final push didn't go through because of network issues. The link to the article and the scripts should be up now.

**Comment by TimNagle-McNaughton** [comment]
Great! Congrats
